NAIVE_BAYES_ID = "0_NAIVE_BAYES"
SVM_ID = "1_SUPPORT_VECTOR_MACHINE"
MULTILAYER_PERCEPTRON_ID = "2_MULTILAYER_PERCEPTRON"
DECISION_TREE_ID = "3_DECISION_TREE"
RANDOM_FOREST_ID = "4_RANDOM_FOREST"
TF_IDF_VECTORIZER_NAME = "./TF_IDF_VECTORIZER"
DATA_KEY = "data"
TARGET_KEY = "target"
PREPROCESSED_DATA_FILE = "./output.csv"
N_FOLDS = 5
ALGORITHM_LABELS = {
    NAIVE_BAYES_ID: "Naive Bayes",
    SVM_ID: "Support Vector Machine",
    MULTILAYER_PERCEPTRON_ID: "Multilayer Perceptron",
    DECISION_TREE_ID: "Decision Tree",
    RANDOM_FOREST_ID: "Random Forest",
}

ALGORITHM_SHORT_LABELS = {
    NAIVE_BAYES_ID: "NB",
    SVM_ID: "SVM",
    MULTILAYER_PERCEPTRON_ID: "MP",
    DECISION_TREE_ID: "DT",
    RANDOM_FOREST_ID: "RF",
}

INPUT_DATA_INDEX = 0
INPUT_TARGET_INDEX = 2