NAIVE_BAYES_ID = "NAIVE_BAYES"
SVM_ID = "SUPPORT_VECTOR_MACHINE"
MULTILAYER_PERCEPTRON_ID = "MULTILAYER_PERCEPTRON"
DECISION_TREE_ID = "DECISION_TREE"
RANDOM_FOREST_ID = "RANDOM_FOREST"
TF_IDF_VECTORIZER_NAME = "./TF_IDF_VECTORIZER"
DATA_KEY = "data"
TARGET_KEY = "target"
PREPROCESSED_DATA_FILE = "./output.csv"
N_FOLDS = 5
ALGORITHM_LABELS = {
    NAIVE_BAYES_ID: "Naive Bayes",
    SVM_ID: "Support Vector Machine",
    MULTILAYER_PERCEPTRON_ID: "Multilayer Perceptron",
    DECISION_TREE_ID: "Decision Tree",
    RANDOM_FOREST_ID: "Random Forest",
}

INPUT_DATA_INDEX = 0
INPUT_TARGET_INDEX = 2